### ISSUE TITLE
Required changes for Q blobs

### ISSUE THREAD

**Issue by trautamaki** [crdroidandroid/android_kernel_oneplus_msm8998#3]
Hi,
What were the required changes to boot with Q blobs?
Thanks!

**Comment by neobuddy89** [comment]
I merged CAF tag LA.UM.8.4.1.r1-01100-8x98.0 with Oneplus kernel.

https://source.codeaurora.org/quic/la/kernel/msm-4.4/tag/?h=LA.UM.8.4.1.r1-01100-8x98.0
