### ISSUE TITLE
Charge

### ISSUE THREAD

**Issue by umerov1999** [crdroidandroid/android_kernel_oneplus_msm8998#4]
In new version this kernel, Oneplus 5 doesn't charging. Reboot fixed this problem, but the bug then appears again if you remove it from the charge and put it back after a short time.  Before clang 12, everything works

**Comment by gwolf2u** [comment]
please follow support forum for support question like this
issue might be indeed clang, but ask in forum with proper logcat and information attached
you can see device support forum url by seeking in our website at https://crdroid.net
