### ISSUE TITLE
Not work camera

### ISSUE THREAD

**Issue by umerov1999** [crdroidandroid/android_kernel_oneplus_msm8998#5]
If i compiled, and flash this kernel on crdroid 7.4, Stok SnapCamera not work. Am I doing the right thing to build branch 10?

Snap:SettingsManager.java getSupportedVideoEncoderForAutoTest IndexOverflowException

OMX.encoders types not found
avc
hevc
h263
mpeg4

**Comment by umerov1999** [comment]
OMX.encoders types not found

**Comment by umerov1999** [comment]
If i disable CLANG LTO, Camera work normal

**Comment by neobuddy89** [comment]
Tested on 10.0 and 11.0. Works fine.
Perhaps, not compiling properly with LLD?

**Comment by umerov1999** [comment]
> Tested on 10.0 and 11.0. Works fine.
> Perhaps, not compiling properly with LLD?

After the 7.5 release, everything worked fine with lto.  The bug was before
